// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrvfvyicdirtnbjfnqzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydmZ2eWljZGlydG5iamZucXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTU1NDMsImV4cCI6MjA2MTI5MTU0M30.zoQjmn_-Zi22PQNa8DZIOyMN-ggwWXpTU6ifwkL53a8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);